# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(253, 101)
        self.ToTrayCheck = QtWidgets.QCheckBox(Form)
        self.ToTrayCheck.setGeometry(QtCore.QRect(10, 20, 131, 18))
        self.ToTrayCheck.setObjectName("ToTrayCheck")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.ToTrayCheck.setText(_translate("Form", "Сворачивать в трей?"))
